ALTER SESSION SET CONTAINER = CDB$ROOT;

GRANT C##role_admin1 TO C##ADMIN_USER;
GRANT C##role_operator TO C##OPERATOR_USER;
GRANT C##role_analyst TO C##ANALYST_USER;
GRANT C##role_analyst TO C##GUEST_USER;

REVOKE SELECT ON SYSTEM.ORDERS FROM C##ANALYST_USER;

