ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE ROLE C##role_admin1;
CREATE ROLE C##role_operator;
CREATE ROLE C##role_analyst;

GRANT CREATE TABLE, CREATE USER, DROP USER TO C##role_admin1;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Orders TO C##role_admin1;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Payments TO C##role_admin1;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Channels TO C##role_admin1;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Movies TO C##role_admin1;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Subscribers TO C##role_admin1;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Tariffs TO C##role_admin1;

GRANT INSERT, UPDATE, DELETE ON SYSTEM.ORDERS TO C##role_operator;
GRANT INSERT, UPDATE, DELETE ON SYSTEM.PAYMENTS TO C##role_operator;

GRANT SELECT ON SYSTEM.ORDERS TO C##role_analyst;
GRANT SELECT ON SYSTEM.PAYMENTS TO C##role_analyst;
GRANT SELECT ON SYSTEM.SUBSCRIBERS TO C##role_analyst;