ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE USER C##ADMIN_USER IDENTIFIED BY Admin_1;
CREATE USER C##OPERATOR_USER IDENTIFIED BY Operator_1;
CREATE USER C##ANALYST_USER IDENTIFIED BY Analyst_1;
CREATE USER C##GUEST_USER IDENTIFIED BY Guest_1;

GRANT CREATE SESSION TO C##ADMIN_USER;
GRANT CONNECT,RESOURCE, CREATE TABLE, CREATE USER, DROP USER TO C##ADMIN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Orders TO C##ADMIN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Payments TO C##ADMIN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Channels TO C##ADMIN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Movies TO C##ADMIN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Subscribers TO C##ADMIN_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.Tariffs TO C##ADMIN_USER;

GRANT CREATE SESSION TO C##OPERATOR_USER;
GRANT INSERT, UPDATE, DELETE ON SYSTEM.Orders TO C##OPERATOR_USER;
GRANT INSERT, UPDATE, DELETE ON SYSTEM.Payments TO C##OPERATOR_USER;

GRANT CREATE SESSION TO C##ANALYST_USER;
GRANT SELECT ON SYSTEM.Orders TO C##ANALYST_USER;
GRANT SELECT ON SYSTEM.Payments TO C##ANALYST_USER;
GRANT SELECT ON SYSTEM.Subscribers TO C##ANALYST_USER;

GRANT CREATE SESSION TO C##GUEST_USER;
GRANT SELECT ON SYSTEM.Subscribers TO C##GUEST_USER;


